### ISSUE TITLE
Cannot fin an overload for "GetDefaultData" and the argument count: 3

### ISSUE THREAD

**Issue by btruong806** [pkjaer/tridion-powershell-modules#11]
Hi Peter,
I installed the Tridion Powershell modules into a brand new working sdl web 8 system and the install went successfully.

So I tried out the commandlet 'New-TridionUser' but got the above error.

Any idea on what is the issue here ?
![new-tridionuser](https://cloud.githubusercontent.com/assets/16419838/11987301/7f4ac97c-a991-11e5-9c9f-1c6b57416322.png)

**Comment by pkjaer** [comment]
Hi there!

Did you set the version to "Web-8.1" using Set-TridionCoreServiceSettings?
Something like this:
Set-TridionCoreServiceSettings -Version Web-8.1 -Persist

**Comment by btruong806** [comment]
Thanks Peter,The suggestion:Set-TridionCoreServiceSettings -Version Web-8.1 -Persist
works!
 

    On Wednesday, December 23, 2015 11:45 PM, Peter Kjaer <notifications@github.com> wrote:
 

 Hi there!Did you set the version to "Web-8.1" using Set-TridionCoreServiceSettings?
Something like this:
Set-TridionCoreServiceSettings -Version Web-8.1 -Persist—

**Comment by pkjaer** [comment]
Great! I will keep this issue open for now while I investigate it, because it really should have worked even before you did that. But good luck using the modules and let us know if you run into any other issues :)
