### ISSUE TITLE
Publish tridion-powershell-modules on a public module repository

### ISSUE THREAD

**Issue by jhorsman** [pkjaer/tridion-powershell-modules#18]
PowerShell 5.0 introduced [PowerShell Get](https://blogs.msdn.microsoft.com/mvpawardprogram/2014/10/06/package-management-for-powershell-modules-with-powershellget/) and it is now possible to install a PowerShell module from a public repository like the [PowerShell Gallery](https://www.powershellgallery.com/).

The installation process for the tridion-powershell-modules would simply be `Install-Module Tridion-CoreService`.

**Comment by jhorsman** [comment]
Please tag this as an enhancement

**Comment by pkjaer** [comment]
Tridion-CoreService can now be found on PowerShell Gallery and the readme has been updated to reflect that.
