### ISSUE TITLE
Getting error Import-Module : The specified module 'Tridion-CoreService' was not loaded because no valid module file was found in any module directory.

### ISSUE THREAD

**Issue by saisravan1936** [pkjaer/tridion-powershell-modules#44]
I am new to Powershell trying to setup environment[tridion-powershell-modules] in my local machine.
I have installed required modules based on the article [https://docs.microsoft.com/en-us/powershell/gallery/psget/overview].
When i run command getting below error

PS C:\Windows\system32> Import-Module -Name Tridion-CoreService
Import-Module : The specified module 'Tridion-CoreService' was not loaded because no valid module file was found in any module directory.
At line:1 char:1
+ Import-Module -Name Tridion-CoreService
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (Tridion-CoreService:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by pkjaer** [comment]
Which version of PowerShell are you using? You can see this by typing the following in PowerShell:
(get-host).Version

If this version is 5 or higher, you do not need to bother with PsGet. 

Also, did you actually call "Install-Module -Name Tridion-CoreService"? Did it give any errors?

**Comment by saisravan1936** [comment]
I have upgraded PowerShell to latest version. Now i dont see that error. 

Thank you Peter.

**Comment by pkjaer** [comment]
Oh okay. Glad to hear it's working for you. Just let me know if you run into anything else.
