### ISSUE TITLE
Trying to connect to remote Tridion server using Powershell Modules

### ISSUE THREAD

**Issue by annjensen** [pkjaer/tridion-powershell-modules#52]
Hi,
I am new to Tridion and want to investigate using the Tridion Powershell Modules to access and manipulate our CMS files.
I have used the following link [Connecting remotely to Core Services using the Tridion Powershell Modules](https://community.sdl.com/product-groups/sdl-tridion/tridion-sites/tridion-developer/b/weblog/posts/connecting-remotely-to-core-services-using-the-tridion-powershell-modules) to try to connect to our remote Tridion server but am getting error on calling $client.GetCurrentUser().
 ~~~~~~~~~~~~~~~~~~~~~~~~
Exception calling "GetCurrentUser" with "0" argument(s): "Could not connect to
net.tcp://<hostname>:2660/CoreService/2012/netTcp. The connection attempt lasted for a time span of 00:00:21.0035230. TCP
error code 10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection
failed because connected host has failed to respond <ip address>:2660. "
At line:1 char:1
 $client.GetCurrentUser()

     CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
     FullyQualifiedErrorId : EndpointNotFoundException
 ~~~~~~~~~~~~~~~~~~~~~~~~
My questions are - can I be confident that the Core Service is running on the remote server or is there something that I need to configure there? and do you see anything obvious that I can follow up on in the error message?

Any feedback appreciated,
Regards,
Ann

**Comment by pkjaer** [comment]
Hi Ann,

There are two ways the Core Service is hosted: one is in the Content Manager Service Host service and the other is in IIS.
The one in the service is hosted on port 2660 and uses netTcp for communication. This is the one you are attempting to connect to (based on the error message) and it is most likely failing due to a firewall blocking the port. 

For such a use case (remote server, firewall likely blocking it) I would recommend simply switching the ConnectionType to something other than netTcp. Start by setting it back to Default and see if that works. When you use the other types, it will instead connect to the Core Service hosted in IIS - and those ports are typically allowed by firewalls (since the CME needs to be accessible :))

**Comment by annjensen** [comment]
Thanks for you reply Peter. I tried the Default connectiontype but am getting a different error
~~~~~~~~~~~~~~~~~~~~~~~~
Exception calling "GetCurrentUser" with "0" argument(s): "There was no endpoint listening at
<hostname>/webservices/CoreService2012.svc/wsHttp that could accept the message. This is often caused by an
incorrect address or SOAP action. See InnerException, if present, for more details."
At line:1 char:1
+ $client.GetCurrentUser()
+ 
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : EndpointNotFoundException`
~~~~~~~~~~~~~~~~~~~~~~~~
Is there a way that I can confirm the host name and availability of the required service on the server?
Thanks again,
An

**Comment by pkjaer** [comment]
You can always try to open the URL (the EndpointUrl returned from Get-TridionCoreServiceSettings) in your browser. 
It won't actually work but if you get an error from WCF it's a good indication that it's running at that URL.

Just to clarify: I was assuming that when you posted the errors here, you removed the first part of the URL yourself and replaced it with `<hostname>` - is that right?

**Comment by annjensen** [comment]
So, I just found out that SDL Tridion is not SDL Tridion Docs (facepalm). 
I want to connect to and manipulate files on a SDL Tridion Docs server and have been advised to use [ISHRemote](https://github.com/sdl/ISHRemote) instead. Does this make sense to you?
Regards,
Ann

**Comment by pkjaer** [comment]
Aha! Indeed these modules are only applicable for Tridion Sites. For Docs it makes sense to use ISHRemote instead.
Good luck!
