### ISSUE TITLE
First run connects to 2011 endpoint

### ISSUE THREAD

**Issue by pkjaer** [pkjaer/tridion-powershell-modules#8]
This seems to persist even after calling Set-TridionCoreServiceSettings, until PowerShell is restarted.

We should change the default to 2013 SP1 anyway, but also find out why it seems to still connect to the wrong endpoint.

**Comment by jhorsman** [comment]
Consider to set the default to the oldest supported CoreService contract supported in the latest SDL Tridion release.

**Comment by pkjaer** [comment]
It is currently set to 2011 and since the endpoints aren't removed, it would stay that way forever. However most people I've seen that use the tools do so on 2013 SP1 -- hence the reason I thought to change the default.

**Comment by pkjaer** [comment]
The problem is actually not with the endpoint, but the client assembly. Since the other version has been loaded into memory, that is being used instead of the new one.

There's no way to unload assemblies from the appdomain in .NET and PowerShell runs in a single appdomain. That makes this tricky to fix.

**Comment by pkjaer** [comment]
I decide to leave the default version at 2011-SP1. It will now give you an error if you try to use different versions in the same PowerShell session (so you at least know what is going on and how to fix it)
