### ISSUE TITLE
Module provides core service client assembly (7.1.0.1245) for 2013-SP1 

### ISSUE THREAD

**Issue by DominicCronin** [pkjaer/tridion-powershell-modules#9]
The version of the core service client in the /bin/client directory of my Tridion installation is 7.1.0.1290. The assembly shipped with the module: Tridion.ContentManager.CoreService.Client.2013sp1.dll is version 7.1.0.1245

**Comment by pkjaer** [comment]
Good catch! I updated it to version 7.1.0.1290.
